import { Metadata } from "next";

export const explainVersionMetadata: Metadata = {
    title: "ExplainVersion",
    description: "Sanity check your semver versioning",
    keywords: [
        'Semantic Versioning',
        'SemVer',
        'Versioning System',
        'Software Versioning',
        'Version Control',
        'Major Version',
        'Minor Version',
        'Patch Version',
        'Version Management',
        'Release Versioning',
        'Version Update',
        'Versioning Rules',
        'Software Updates',
        'Versioning Best Practices',
        'Dependency Management',
        'Versioning Guidelines',
        'Semantic Version Validator',
        'Versioning Syntax',
        'SemVer Specification',
        'Versioning Standards',
        'Version Compatibility',
        'Version Increment',
        'Versioning Tool',
        'Automated Versioning',
        'Versioning Strategy',
        'Version Identifier',
        'Breaking Changes',
        'Backward Compatibility',
        'Version Tags',
        'Pre-release Version',
        'Build Metadata',
        'Software Release Cycle',
        'Continuous Integration',
        'Versioning Examples',
        'Versioning Documentation',
        'SemVer Explained',
        'SemVer Tutorial',
        'Versioning Practices',
        'Versioning for Developers',
        'Version History',
        'Versioning FAQ',
        'Versioning for Projects',
        'Versioning Automation',
        'Versioning Implementation',
        'Versioning Workflow',
        'API Versioning',
        'Versioning Convention',
        'SemVer Checker',
        'Versioning in Node.js',
        'Versioning in JavaScript',
        'Next.js Versioning',
        'Open Source Versioning',
        'Software Development Versioning',
        'Versioning Guide',
        'Software Lifecycle',
        'Versioning in Agile',
        'Release Management',
        'Version Numbering',
        'Version Control System',
        'Version Management Tool',
        'Project Versioning',
        'Versioning Tips',
        'Git Versioning',
        'Software Deployment',
        'Versioning Resources',
        'Semantic Versioning Validator',
        'Versioning Explained',
        'Version Update Process',
        'Versioning in CI/CD',
        'Software Maintenance',
        'Versioning Standards Guide',
        'Versioning for Teams',
        'Versioning Explained Simply',
        'Version Numbering Guide',
        'Understanding Semantic Versioning',
        'Versioning and Dependencies',
        'Managing Software Versions',
        'Versioning Tutorial for Beginners',
        'Effective Versioning Strategies',
        'Software Versioning Explained',
        'Semantic Versioning Basics',
        'Versioning Practices for Software Projects',
        'Version Management Best Practices',
        'Semantic Versioning Tools',
        'Versioning in Modern Software Development',
        'Version Control and Management',
        'Best Practices for Semantic Versioning',
        'Advanced Versioning Techniques',
        'Versioning in Open Source Projects',
        'Implementing Semantic Versioning',
        'Versioning Concepts',
        'Versioning Strategies and Practices',
        'Versioning Automation Tools',
        'Software Development Lifecycle',
        'Versioning in DevOps',
        'Versioning in Continuous Deployment',
        'Importance of Semantic Versioning',
        'Semantic Versioning for APIs',
        'Software Project Versioning',
        'Best Versioning Practices for Developers'
    ].join(', '),
};
