import type { Metadata } from "next";
import { Inter, Poppins, Aldrich } from "next/font/google";
import { ThemeContextProvider } from "@/context/ThemeContext";

import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter"
})

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins",
})

const aldrich = Aldrich({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-aldrich",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" >
            <body className={`${inter.variable} ${poppins.variable} ${aldrich.variable}`} >
                <ThemeContextProvider>
                    {children}
                </ThemeContextProvider>
            </body>
        </html >
    );
}
